:       BELL on.
:	day range = 15 (14 days ahead).

 1 jul (wed) - phone bill due:                                  $32.37. Pd
 1 jul (wed) - Computer phone bill due:                         $12.94. Pd
 2 jul (thu) - PCSC ZIP loan pmnt due:                          $13.00. Pd
 3 jul (fri) - payday:                                 $424.56.
 4 jul (sat) - Sears chg pmnt due:                              $21.00. Pd
10 jul (fri) - Gibr mtge pmnt due:                             $172.21. Pd
10 jul (fri) - Pub Strg Mgt, 925 Filipe, SJ 95122, due:         $40.00. Pd
10 jul (fri) - Greenwood Trust: Discover Card pmnt due:         [Nancy Pd]
10 jul (fri) - payday:                                 $424.56.
15 jul (wed) - Scher & Bassett, atty's.:                        $25.00. Pd
16 jul (thu) - AAA membership due:                              $52.00. Pd
17 jul (fri) - payday:                                 $424.56.
18 jul (sat) - Sprint bill due:                                  $5.69. Pd
18 jul (sat) - Citibank VISA chg pmnt due:                     $194.00. Pd
20 jul (mon) - SSB mtge pmnt due:                              $193.60. Pd
22 jul (wed) - Reader's Digest Cond. Books bill due:            $12.78. Pd
23 jul (thu) - Water bill due:                                  $30.93. Pd
24 jul (fri) - Chevron chg pmnt due:                            $98.23. Pd
24 jul (fri) - payday:                                 $424.56.
27 jul (mon) - PG&E pmnt due:                                   $71.87. Pd
28 jul (tue) - Penny chg pmnt due:                              $50.00. Pd
29 jul (wed) - Bank One MasterCard pmnt due:                    $59.00. Pd
31 jul (fri) - payday:                                 $424.56.

 1 aug (sat) - EAC FCU VISA pmnt due:                           $25.00. Pd
 1 aug (sat) - phone bill due:                                  $44.25. Pd
 1 aug (sat) - Computer phone bill due:                         $14.34. Pd
 2 aug (sun) - PCSC ZIP loan pmnt due:                          $13.00. Pd
 4 aug (tue) - Sears chg pmnt due:                              $21.00. Pd
 7 aug (fri) - Insurance premium, yellow Datsun:               $185.14. Pd
 7 aug (fri) - payday:                                 $424.56.
10 aug (mon) - Pub Strg Mgt, 925 Filipe, SJ 95122, due:         $40.00. Pd
10 aug (mon) - Greenwood Trust: Discover Card pmnt due:         [Nancy Pd]
14 aug (fri) - payday:                                 $424.56.
15 aug (sat) - Gibr mtge pmnt due:                             $172.21. Pd
15 aug (sat) - Scher & Bassett, atty's.:                        $25.00. Pd
15 aug (sat) - Nancy's Shell Oil bill due:                       $8.26. Pd
17 aug (mon) - Sprint bill due:                                 $20.68. Pd
17 aug (mon) - Shell Oil pmnt due:                              $67.98. Pd
18 aug (tue) - Citibank VISA chg pmnt due:                     $194.00. Pd
20 aug (thu) - SSB mtge pmnt due:                              $193.60. Pd
21 aug (fri) - payday:                                 $424.56.
23 aug (sun) - Water bill due:                                  $53.81. Pd
23 aug (sun) - Chevron chg pmnt due:                            $63.13. Pd
25 aug (tue) - S.C. Cnty: Ted's stay:                           $50.00. Pd
27 aug (thu) - PG&E pmnt due:                                   $79.14. Pd
28 aug (fri) - Penny chg pmnt due:                              $70.00. Pd
28 aug (fri) - Reader's Digest, book:                           $22.13. Pd
28 aug (fri) - State Farm Ins:  Homeowner's, pmnt due:         $168.09. Pd
28 aug (fri) - payday:                                 $424.56.
29 aug (sat) - Bank One MasterCard pmnt due:                    $60.00. Pd
29 aug (sat) - Science News subscription due:                   $25.17. Pd

 1 sep (tue) - EAC FCU VISA pmnt due:                           $30.00. Pd
 1 sep (tue) - phone bill due:                                  $68.21. Pd
 1 sep (tue) - Minh Thieu:  Merc. News subscr. due:              $5.00. Pd
 1 sep (tue) - Computer phone bill due:                         $14.24. Pd
 2 sep (wed) - PCSC ZIP loan pmnt due:                          $13.00. Pd
 3 sep (thu) - State Farm:  Datsun wagon ins. due:              $75.01. Pd
 4 sep (fri) - Sears chg pmnt due:                              $50.00. Pd
 4 sep (fri) - payday:                                 $424.56.
10 sep (thu) - Pub Strg Mgt, 925 Filipe, SJ 95122, due:         $40.00. Pd
10 sep (thu) - Greenwood Trust: Discover Card pmnt due:           Nancy Pd
11 sep (fri) - Smithsonian subscr. due:                         $20.00. Pd
11 sep (fri) - payday:                                 $436.37.
14 sep (mon) - Berkeley Wellness Letter subscri. due:           $15.00. Pd
15 sep (tue) - Gibr mtge pmnt due:                             $172.21. Pd
15 sep (tue) - Scher & Bassett, atty's.:                        $15.00. Pd
17 sep (thu) - Shell Oil chg pmnt. due:                         $58.23. Pd
17 sep (thu) - Sprint bill due:                                     $_____.
18 sep (fri) - Citibank VISA chg pmnt due:                     $194.00. Pd
18 sep (fri) - payday:                                 $436.37.
20 sep (sun) - SSB mtge pmnt due:                                  $193.60.
20 sep (sun) - S.C. Cnty: Ted's stay:                               $50.00.
21 sep (mon) - Chevron chg pmnt due:                                $27.98.
21 sep (mon) - Water bill due:                                      $43.91.
25 sep (fri) - payday:                                 $436.37.
26 sep (sat) - Penny chg pmnt due:                                  $55.00.
27 sep (sun) - PG&E pmnt due:                                       $67.45.
29 sep (tue) - Bank One MasterCard pmnt due:                        $59.00.
30 sep (wed) - Reader's Digest, book:                               $13.85.
30 sep (wed) - Waste Management bill due:                           $17.97.

 1 oct (thu) - EAC FCU VISA pmnt due:                               $_____.
 1 oct (thu) - phone bill due:                                      $39.11.
 1 oct (thu) - Computer phone bill due:                             $13.66.
 2 oct (fri) - PCSC ZIP loan pmnt due:                              $13.00.
 2 oct (fri) - payday:                                 $436.37.
 4 oct (sun) - Sears chg pmnt due:                                  $50.00.
 9 oct (fri) - payday:                                 $436.37.
10 oct (sat) - Pub Strg Mgt, 925 Filipe, SJ 95122, due:             $40.00.
10 oct (sat) - Greenwood Trust: Discover Card pmnt due:             $_____.
15 oct (thu) - Gibr mtge pmnt due:                                 $172.21.
15 oct (thu) - Scher & Bassett, atty's.:                            $25.00.
16 oct (fri) - payday:                                 $436.37.
17 oct (sat) - Shell Oil chg pmnt. due:                             $_____.
17 oct (sat) - Sprint bill due:                                     $_____.
18 oct (sun) - Citibank VISA chg pmnt due:                         $194.00.
20 oct (tue) - SSB mtge pmnt due:                                  $193.60.
20 oct (tue) - S.C. Cnty: Ted's stay:                               $50.00.
23 oct (fri) - Water bill due:                                      $_____.
23 oct (fri) - Chevron chg pmnt due:                                $_____.
23 oct (fri) - payday:                                 $436.37.
20 oct (tue) - S.C. Cnty: Ted's stay:                               $50.00.
26 oct (mon) - Penny chg pmnt due:                                  $55.00.
27 oct (tue) - PG&E pmnt due:                                       $_____.
29 oct (thu) - Bank One MasterCard pmnt due:                        $60.00.
30 oct (fri) - payday:                                 $436.37.

 1 nov (thu) - EAC FCU VISA pmnt due:                               $_____.
 1 nov (thu) - phone bill due:                                      $39.11.
 1 nov (thu) - Computer phone bill due:                             $13.66.
 2 nov (fri) - PCSC ZIP loan pmnt due:                              $13.00.
 2 nov (fri) - payday:                                 $436.37.
 3 nov (tue) - State Farm:  Datsun wagon ins. due:                  $73.01.
 4 nov (sun) - Sears chg pmnt due:                                  $50.00.
 9 nov (fri) - payday:                                 $436.37.
10 nov (sat) - Pub Strg Mgt, 925 Filipe, SJ 95122, due:             $40.00.
10 nov (sat) - Greenwood Trust: Discover Card pmnt due:             $_____.
15 nov (thu) - Gibr mtge pmnt due:                                 $172.21.
15 nov (thu) - Scher & Bassett, atty's.:                            $25.00.
16 nov (fri) - payday:                                 $436.37.
17 nov (sat) - Shell Oil chg pmnt. due:                             $_____.
17 nov (sat) - Sprint bill due:                                     $_____.
18 nov (sun) - Citibank VISA chg pmnt due:                         $194.00.
20 nov (tue) - SSB mtge pmnt due:                                  $193.60.
20 nov (tue) - S.C. Cnty: Ted's stay:                               $50.00.
23 nov (fri) - Water bill                                      $_____.
23 nov (fri) - Chevron chg pmnt due:                                $_____.
23 nov (fri) - payday:                                 $436.37.
20 nov (tue) - S.C. Cnty: Ted's stay:                               $50.00.
26 nov (mon) - Penny chg pmnt due:                                  $55.00.
27 nov (tue) - PG&E pmnt due:                                       $_____.
29 nov (thu) - Bank One MasterCard pmnt due:                        $60.00.
30 nov (fri) - payday:                                 $436.37.



31 jul (fri) - Finish SPOOL monthly, RDIST doc, rsrch Fayez, printer prob.

29 aug (sat) - P.A.: retreat, dinner, Dr. Science 

11 sep (fri) 6:30 pm -   potluck & Bus. Mtg.
15 sep (tue) 9:30 am -   Mort, @Kaiser, Fremont, on Liberty.
19 sep (sat) -           QSQ retreat.
20 sep (sun) -           QSQ retreat.
27 sep (sun) -           Harvest Festival.
29 sep (tue) 10:45 am -  Dr. Kalb, Kaiser S.C., bldg A (modular, last on rt)
  jWM(